### ISSUE TITLE
Edit & Update Button

### ISSUE THREAD

**Issue by AriDevK** [louire/Todo-RustSvelte#1]
At this moment the update event is set into a button with the text "Update" which is not very explicit because you need first change the value and then click the button.

Would be great if the "update" button text is set to "edit" by default and when I click on it the text changes to "update" and focus on the input to have a visual help of what I am editing.

It will be great if you implement this :3

![anime-girl](https://i.pinimg.com/originals/6d/c6/f3/6dc6f317a753e3496330684f4751f543.gif)

**Comment by louire** [comment]
👍🏻🙌🏻🤝🏻
