### ISSUE TITLE
Readme Defects

### ISSUE THREAD

**Issue by AriDevK** [louire/Todo-RustSvelte#2]
On readme file, the sqlx-cli section code block do not match with the actual repository git clone and cd commands.

### Actual
```md
git clone https://github.com/knarkzel/todo
cd todo/
```

### Should be
```md
git clone https://github.com/louire/Todo-RustSvelte.git
cd Todo-RustSvelte/
```

<br> 
<br> 
Also the Tokio badge do not show the tool icon, it can be placed by base64 image format.

Have a nice day :3
![uwu](https://i.pinimg.com/564x/c0/93/1b/c0931bfd307ffca791340453407d1f07.jpg)

**Comment by louire** [comment]
good job!
